// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeepAttachments } from "./KeepAttachments";
import type { MessageRef } from "./MessageRef";

export type ComposeRequest = { 
/**
 * Comma-separated, `Name <addr>` or bare addresses.
 */
to: string, cc: string, bcc: string, subject: string, text: string, uploads: Array<string>, keep: KeepAttachments | null, in_reply_to: string | null, references: Array<string>, 
/**
 * Gets \Answered once sent.
 */
reply_of: MessageRef | null, 
/**
 * Gets $Forwarded once sent.
 */
forward_of: MessageRef | null, 
/**
 * The draft this compose was saved as; replaced on save, removed on send.
 */
draft: MessageRef | null, 
/**
 * Rich-text body. When present, `text` is its plain-text alternative.
 */
html: string | null, 
/**
 * Uploads the HTML references as `cid:<upload id>` (pasted / dropped images).
 */
inline_uploads: Array<string>, 
/**
 * Sender name / Reply-To come from this identity; `None` uses the default.
 */
identity: number | null, };
