// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Contact = { id: number, name: string, email: string, 
/**
 * False for addresses only collected from sent mail.
 */
saved: boolean, };
