// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateFolderRequest = { 
/**
 * Wire path of the parent, or `None` for top level.
 */
parent: string | null, 
/**
 * Display name; the server encodes it.
 */
name: string, };
