// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlagName } from "./FlagName";

export type FlagRequest = { folder: string, uids: Array<number>, flag: FlagName, value: boolean, };
