// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Flags = { seen: boolean, flagged: boolean, answered: boolean, forwarded: boolean, draft: boolean, };
