// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Special } from "./Special";

export type Folder = { 
/**
 * The IMAP name, exactly as the server spells it (modified UTF-7). Send this back.
 */
path: string, 
/**
 * Human-readable leaf name.
 */
name: string, delimiter: string | null, special: Special | null, selectable: boolean, total: number, unread: number, };
