// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Identity = { 
/**
 * Absent for the built-in identity of an account that has not saved any.
 */
id: number | null, 
/**
 * Always the login address.
 */
email: string, name: string, reply_to: string, signature: string, is_default: boolean, };
