// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IdentityInput = { id: number | null, name: string, reply_to: string, signature: string, is_default: boolean, };
