// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Attachment } from "./Attachment";
import type { Flags } from "./Flags";

export type MessageDetail = { folder: string, uid: number, subject: string, from: Address | null, to: Array<Address>, cc: Array<Address>, 
/**
 * Only present on your own stored copies (Sent, Drafts).
 */
bcc: Array<Address>, reply_to: Array<Address>, date: string | null, message_id: string | null, in_reply_to: string | null, references: Array<string>, flags: Flags, 
/**
 * A complete, sanitized HTML document for a sandboxed `<iframe srcdoc>`. Never insert
 * it into the app's own DOM.
 */
html: string | null, text: string | null, 
/**
 * True when remote images were stripped; re-request with `images=1` to allow them.
 */
remote_images_blocked: boolean, attachments: Array<Attachment>, };
