// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSummary } from "./MessageSummary";

export type MessagePage = { folder: string, total: number, page: number, page_size: number, messages: Array<MessageSummary>, };
