// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { Flags } from "./Flags";

export type MessageSummary = { uid: number, subject: string, from: Address | null, to: Array<Address>, 
/**
 * RFC 3339.
 */
date: string | null, size: number, flags: Flags, has_attachments: boolean, 
/**
 * Messages with the same key belong to one conversation (root of References).
 */
thread_key: string, message_id: string | null, 
/**
 * How many ancestors the message names (References, else In-Reply-To): a reply is
 * always deeper than what it answers, which orders a thread when dates tie.
 */
depth: number, };
