// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where messages went, so the UI can offer Undo (a move back from `to`).
 */
export type MoveResult = { 
/**
 * Destination folder; `None` when the messages were deleted permanently.
 */
to: string | null, 
/**
 * Their UIDs in `to`.
 */
uids: Array<number>, };
