// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PublicConfig = { app_name: string, version: string, license: string, 
/**
 * Where to get the source of the version running here (AGPL-3.0 §13).
 */
source_url: string, };
