// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When remote images in HTML mail load without asking.
 */
export type RemoteImages = "never" | "contacts" | "always";
