// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenameFolderRequest = { folder: string, 
/**
 * New display name for the last path segment.
 */
name: string, };
