// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSummary } from "./MessageSummary";

export type SearchHit = { 
/**
 * Wire path of the folder the message is in.
 */
folder: string, message: MessageSummary, };
