// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

/**
 * A conversation: every message sharing the opened one's thread, across its folder,
 * Inbox and Sent, oldest first, one entry per Message-ID.
 */
export type Thread = { items: Array<SearchHit>, };
