// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Upload = { id: string, filename: string, content_type: string, size: number, };
